---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/
resources:
  - route-hello.yml
  - route-hello-proxy.yml
  - rbac.yml

images:
  - name: "hello-impl"
    newName: "docker-registry-default.centralpark.lightbend.com/lagom-java-minimal-deployment-example/hello-impl"
    newTag: "1.1-SNAPSHOT"
  - name: "hello-proxy-impl"
    newName: "docker-registry-default.centralpark.lightbend.com/lagom-java-minimal-deployment-example/hello-proxy-impl"
    newTag: "1.1-SNAPSHOT"