---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "hello-proxy-lagom-minimal-service-v1-0-snapshot"
  labels:
    appName: "hello-proxy-lagom-minimal-service"
    appNameVersion: "hello-proxy-lagom-minimal-service-v1-0-snapshot"
spec:
  replicas: 1
  selector:
    matchLabels:
      appNameVersion: "hello-proxy-lagom-minimal-service-v1-0-snapshot"
  template:
    metadata:
      labels:
        appName: "hello-proxy-lagom-minimal-service"
        appNameVersion: "hello-proxy-lagom-minimal-service-v1-0-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: "hello-proxy-lagom-minimal-service"
          image: "hello-proxy-impl:1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_OPTS"
              value: "-Dconfig.resource=application-prod.conf -Dplay.server.pidfile.path=/dev/null"
            - name: "DEPLOYMENT_SERVICE_NAME"
              value: "hello-proxy-lagom-minimal-service"
          ports:
            # application
            - name: http
              containerPort: 9000

          resources:
            limits:
              cpu: 0.15
              memory: 512Mi
            requests:
              cpu: 0.15
              memory: 512Mi

      volumes: []