---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "hello-lagom-minimal-service-v1-0-snapshot"
  labels:
    appName: "hello-lagom-minimal-service"
    appNameVersion: "hello-lagom-minimal-service-v1-0-snapshot"
spec:
  replicas: 3
  selector:
    matchLabels:
      appNameVersion: "hello-lagom-minimal-service-v1-0-snapshot"
  template:
    metadata:
      labels:
        appName: "hello-lagom-minimal-service"
        appNameVersion: "hello-lagom-minimal-service-v1-0-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: "hello-lagom-minimal-service"
          image: "hello-impl:1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_OPTS"
              value: "-Dconfig.resource=application-prod.conf -Dplay.server.pidfile.path=/dev/null"
            - name: "DEPLOYMENT_SERVICE_NAME"
              value: "hello-lagom-minimal-service"
          ports:
            # application
            - name: http
              containerPort: 9000
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management
            - name: management
              containerPort: 8558
              protocol: TCP

          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 90

          resources:
            limits:
              cpu: 0.15
              memory: 512Mi
            requests:
              cpu: 0.15
              memory: 512Mi

      volumes: []